CREATE DATABASE login_db;
GRANT ALL PRIVILEGES ON DATABASE login_db TO postgres;
CREATE DATABASE traveler_db;
GRANT ALL PRIVILEGES ON DATABASE traveler_db TO postgres;
CREATE DATABASE catalogue_db;
GRANT ALL PRIVILEGES ON DATABASE catalogue_db TO postgres;
CREATE DATABASE payment_db;
GRANT ALL PRIVILEGES ON DATABASE payment_db TO postgres;